secrets_yaml_example = """
exchanges:
  binance:
    api_key: YOUR_KEY
    api_secret: YOUR_SECRET
  okx:
    api_key: YOUR_KEY
    api_secret: YOUR_SECRET
    passphrase: YOUR_PASSPHRASE
telegram:
  bot_token: YOUR_TG_TOKEN
  chat_id: YOUR_CHAT_ID
"""