app:
  name: crypto_alpha_bot
  timezone: UTC

universe:
  spot: [BTCUSDT, ETHUSDT, SOLUSDT]
  perps: [BTCUSDT, ETHUSDT]

data:
  timeframe: 1h
  ohlcv_limit: 500

risk:
  capital_usd: 10000
  max_risk_pct_trade: 0.5

scoring:
  momentum_w: 0.4
  breakout_w: 0.3
  contrarian_w: 0.3

regime:
  vol_short_window: 24
  vol_long_window: 120
  compress_ratio: 0.6
  expansion_ratio: 1.3

storage:
  path: data/raw

logging:
  level: INFO

bootstrap:
  enabled: false          # Se true roda bootstrap ao iniciar (ou usar flag CLI)
  target_hours: 2000      # Ou use target_candles se preferir
  step_limit: 1000        # Quantidade de candles por requisição (<= 1000 para Binance)

reports:
  path: data/reports
  snapshot_file: snapshots.parquet

derivatives_history:
  enabled: true
  funding:
    lookback_days: 400        # quanto buscar se não houver cache
    step_hours: 200           # janela (horas) por fetch funding (traduz em start/end)
  oi:
    lookback_days: 120
    step_hours: 48
  paths:
    base: data/derivatives
    funding_dir: funding
    oi_dir: oi
  recompute_features: true