app:
  name: crypto_alpha_bot
  timezone: UTC
universe:
  spot: [BTCUSDT, ETHUSDT, SOLUSDT]
scheduler:
  ohlcv_1h: 300
risk:
  capital_usd: 10000
  max_risk_pct_trade: 0.5
scoring:
  momentum_w: 0.4
  breakout_w: 0.3
  contrarian_w: 0.3

  settings_yaml_example = """
# Configurações gerais
app:
  name: crypto_alpha_bot
  timezone: UTC
  base_quote: USDT
  log_level: INFO
  data_retention_days: 365

# Ativos monitorados
universe:
  spot: [BTCUSDT, ETHUSDT, SOLUSDT, BNBUSDT, XRPUSDT, LINKUSDT]
  perps: [BTCUSDT, ETHUSDT, SOLUSDT]
  max_alts: 5

# Datasources
exchanges:
  binance:
    enabled: true
    weight: 0.6
  okx:
    enabled: true
    weight: 0.4

# Frequências de update (segundos)
scheduler:
  ohlcv_1m: 60
  ohlcv_1h: 300
  funding: 600
  orderbook: 30
  metrics_report: 3600
  health: 60

# Risco baseline
risk:
  capital_usd: 10000
  max_risk_pct_trade: 0.5   # % do capital
  max_daily_loss_pct: 2.0
  max_total_exposure_pct: 120
  max_alt_exposure_pct: 40

# Scoring weights base
scoring:
  momentum_w: 0.4
  breakout_w: 0.3
  contrarian_w: 0.3

# Kill switches
kill_switch:
  max_drawdown_pct: 25
  data_anomaly_consecutive: 3
  api_failure_rate_pct: 5

# Meta-labeling
meta_label:
  enabled: false
  model_path: models/meta_label.pkl
"""