app:
  name: crypto_alpha_bot
  timezone: UTC

universe:
  spot: [BTCUSDT, ETHUSDT, SOLUSDT]
  perps: [BTCUSDT, ETHUSDT]

data:
  timeframe: 1h
  ohlcv_limit: 500

risk:
  capital_usd: 10000
  max_risk_pct_trade: 0.5

scoring:
  momentum_w: 0.4
  breakout_w: 0.3
  contrarian_w: 0.3

regime:
  vol_short_window: 24
  vol_long_window: 120
  compress_ratio: 0.6
  expansion_ratio: 1.3

storage:
  path: data/raw

logging:
  level: INFO
